package arief.mahendra.database;

import org.junit.jupiter.api.Test;

import java.sql.*;

public class AutoIncrementTest {
    @Test
    void testAutoIncrement() throws SQLException {

        Connection connection = ConnectionUtil.getHikariDataSource().getConnection();
        String email = "arief@mail.com";
        String comment = "Hello guys";
        String sql = """
                insert into comments(email, comment) values(?,?)
                """;

        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        preparedStatement.setString(1, email);
        preparedStatement.setString(2, comment);
        preparedStatement.executeUpdate();
    }

    @Test
    void testAutoIncrementReturnAutoGeneratedKey() throws SQLException {
        Connection connection = ConnectionUtil.getHikariDataSource().getConnection();
        String email = "arief@mail.com";
        String comment = "Hello guys";
        String sql = """
                insert into comments(email, comment) values(?,?)
                """;

        PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        preparedStatement.setString(1, email);
        preparedStatement.setString(2, comment);
        preparedStatement.executeUpdate();

        ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
        while (generatedKeys.next()){
            int id = generatedKeys.getInt(1);
            System.out.println("ID comment : " + id);
        }
    }
}
